spring:
  data:
    mongodb:
      host: ${MONGO_DB_HOST:localhost}
      port: ${MONGO_DB_PORT:27017}
      username: ${MONGO_DB_USERNAME:admin}
      password: ${MONGO_DB_PASSWORD:admin}
      authentication-database: ${MONGO_DB_AUTHENTICATION_DB:admin}

security:
  require-ssl: ${SSL_ENABLED:false}

server:
  ssl:
    key-store: ${SSL_KEY_STORE_PATH:}
    key-store-password: ${SSL_KEY_STORE_PASSWORD:}
    keyStoreType: ${SSL_KEY_STORE_TYPE:PKCS12}
    keyAlias: ${SSL_KEY_ALIAS:}