spring:
  data:
    mongodb:
      host: ${MONGO_DB_HOST:localhost}
      port: ${MONGO_DB_PORT:27017}
      username: ${MONGO_DB_USERNAME:admin}
      password: ${MONGO_DB_PASSWORD:admin}
      authentication-database: ${MONGO_DB_AUTHENTICATION_DB:admin}

server:
  forward-headers-strategy: native
