spring:
  data:
    mongodb:
      host: ${MONGO_DB_HOST:localhost}
      port: ${MONGO_DB_PORT:27017}
      username: ${MONGO_DB_USERNAME:admin}
      password: ${MONGO_DB_PASSWORD:admin}
      authentication-database: ${MONGO_DB_AUTHENTICATION_DB:admin}
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: ${SECURITY_CLIENT_ID:personal-space-web}
            authorization-grant-type: ${SECURITY_GRANT_TYPE:authorization_code}
            scope: ${SECURITY_SCOPE:openid}
        provider:
          keycloak:
            issuer-uri: ${SECURITY_ISSUER_ID:https://lemur-1.cloud-iam.com/auth/realms/mezzedine-auth-server}
            user-name-attribute: ${SECURITY_USERNAME_ATTRIBUTE:preferred_username}
      resourceserver:
        jwt:
          issuer-uri: ${SECURITY_ISSUER_ID:https://lemur-1.cloud-iam.com/auth/realms/mezzedine-auth-server}

article:
  id:
    hash:
      salt: salt
      size: 8